# Generated by Django 3.1.14 on 2023-03-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mapping", "0123_auto_20210428_1837"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingECLConcept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("module_id", models.CharField(max_length=255)),
                ("effective_time", models.DateField(blank=True, null=True)),
                ("definition_status", models.CharField(max_length=15)),
                ("id_and_fsn_term", models.TextField()),
                ("active", models.BooleanField()),
                ("preferred_title", models.TextField()),
                ("pt_lang", models.CharField(max_length=2)),
                ("fsn", models.TextField()),
                ("fsn_lang", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="mappingcodesystem",
            name="codesystem_title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="mappingcodesystem",
            name="codesystem_version",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="mappingreleasecandidate",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Draft"),
                    ("1", "Active"),
                    ("2", "Retired"),
                    ("3", "Unknown"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mappingtask",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="mapping.mappingproject",
            ),
        ),
        migrations.AlterField(
            model_name="mappingtask",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mappingeclconcept",
            name="ecl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concepts",
                to="mapping.mappingeclpart",
            ),
        ),
        migrations.AddField(
            model_name="mappingeclconcept",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concepts",
                to="mapping.mappingtask",
            ),
        ),
    ]
