# Generated by Django 3.1.14 on 2023-04-06 07:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0125_auto_20230327_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingtask",
            name="exclusions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
