# Generated by Django 3.1.14 on 2023-04-06 07:33

from django.db import migrations


def backport_all_exclusions(apps, _):
    """Backport existing MappingEclPartExclusion to MappingTask.exclusions array."""
    MappingTask = apps.get_model("mapping", "MappingTask")
    MappingEclPartExclusion = apps.get_model("mapping", "MappingEclPartExclusion")

    tasks_to_update = []
    for exclusion in MappingEclPartExclusion.objects.all():
        task = exclusion.task
        task.exclusions = [c for c in exclusion.components if c]
        tasks_to_update.append(task)

    MappingTask.objects.bulk_update(tasks_to_update, ["exclusions"])


def reverse(apps, _):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0126_mappingtask_exclusions"),
    ]

    operations = [
        migrations.RunPython(code=backport_all_exclusions, reverse_code=reverse)
    ]
