# Generated by Django 4.0 on 2023-05-22 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mapping', '0128_mappingeclconcept_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingProjectAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.TextField()),
                ('hit_reason', models.TextField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('ignore', models.BooleanField(default=False)),
                ('sticky', models.BooleanField(default=False)),
                ('first_hit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ignore_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.mappingproject')),
            ],
        ),
    ]
