# Generated by Django 4.0 on 2023-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0129_mappingprojectaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingproject',
            name='ecl_scope',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
