# Generated by Django 4.0 on 2023-05-23 11:31

from django.db import migrations


def add_project_ecl_scope(apps, _):
    MappingProject = apps.get_model("mapping", "MappingProject")

    projects = [
        (9, "< 404684003 |klinische bevinding (bevinding)| "),
        (11, "< 64572001 |aandoening (aandoening)| OR < 71388002 |verrichting (verrichting)|"),
        (12, "< 363679005 |beeldvormende verrichting (verrichting)|"),
        (10, "< 64572001 |aandoening (aandoening)|"),
    ]

    for project_id, scope in projects:
        project = MappingProject.objects.get(pk=project_id)
        project.ecl_scope = scope
        project.save()


def revert(apps, _):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0130_mappingproject_ecl_scope'),
    ]

    operations = [
        migrations.RunPython(add_project_ecl_scope, revert)
    ]
