# Generated by Django 4.0 on 2023-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0131_auto_20230523_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingprojectaudit',
            name='sticky',
        ),
        migrations.AddField(
            model_name='mappingprojectaudit',
            name='extra_1',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingprojectaudit',
            name='extra_2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
